export const GET_ALL_USER_FEE_DATA = 'GET_ALL_USER_FEE_DATA';
export const GET_ALL_USER_FEE_DATA_SUCCESS = 'GET_ALL_USER_FEE_DATA_SUCCESS';
export const GET_ALL_USER_FEE_DATA_FAILURE = 'GET_ALL_USER_FEE_DATA_FAILURE';

export const getAllUserFeeData = () => ({
  type: GET_ALL_USER_FEE_DATA,
});
